feat: Add device service files and make command options
edgexfoundry/developer-scripts pull request #330
Opened 2020-10-20 22:00 UTC by lenny-intel

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/developer-scripts/blob/master/.github/Contributing.md.

## What is the current behavior?

Commented out Device Service are removed when the new compose files are generated
The source compose files have the docker registry name in the file name, but the registry is now an environment variable so could be something different.

## Issue Number:  #329

## What is the new behavior?

Make commands now have options for adding each device service to the generated compose file.
source compose file names have be refactored to simplify and remove the docker registry name.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2020-10-20 22:27 UTC, jim-wang-intel requested changes

2020-10-20 22:27 UTC, jim-wang-intel commented on releases/nightly-build/compose-files/source/Makefile
> +		-f add-device-modbus.yml \
```suggestion
		-f add-device-grove.yml \
```

2020-10-20 22:28 UTC, lenny-intel commented on releases/nightly-build/compose-files/source/Makefile
> +		-f add-device-modbus.yml \
Dang it! Good catch!

2020-10-20 22:34 UTC, lenny-intel commented on releases/nightly-build/compose-files/source/Makefile
> +		-f add-device-modbus.yml \
fixed

2020-10-21 18:32 UTC, jim-wang-intel approved these changes
LGTM

2020-10-21 21:55 UTC, lenny-intel commented
@cherrycl, this PR with minor changes to the committed compose files used by TAF is failing the new smoke tests. Can you please review the failures here and determine why it is failing? I have no clue why :-(
https://jenkins.edgexfoundry.org/blue/rest/organizations/jenkins/pipelines/edgexfoundry/pipelines/edgex-taf-pipelines/branches/smoke-test/runs/17/log/?start=0

BTW, I ran get-compose.sh with and w/o security and the resulting compose files looks good. 
Thanks!

2020-10-21 22:44 UTC, jim-wang-intel submitted a review, later dismissed

2020-10-21 23:48 UTC, jpwhitemn submitted a review, later dismissed
Nuice!  Worked well.  I tested with each of the DS additions and only the Grove had issues (appropriate for x86).

2020-10-22 01:20 UTC, cherrycl commented
@lenny-intel The error occurred by [edgex-taf PR #198](https://github.com/edgexfoundry/edgex-taf/pull/198), not about the compose files. For this PR, you can ignore the failure. I will fix the error on edgex-taf repo.

2020-10-22 03:45 UTC, cherrycl commented
@lenny-intel The merged [edgex-taf PR #208](https://github.com/edgexfoundry/edgex-taf/pull/208) fixed the failed smoke tests.

2020-10-22 16:38 UTC, lenny-intel commented
> The merged [edgex-taf PR #208](https://github.com/edgexfoundry/edgex-taf/pull/208) fixed the failed smoke tests.

@cherrycl , Thank you for the very quick response to this issue!!

2020-10-22 17:57 UTC, jim-wang-intel approved these changes
LGTM

2020-10-22 18:00 UTC, merged