feat(security): Containers run as non-root user
edgexfoundry/developer-scripts pull request #374
Opened 2021-01-08 23:56 UTC by beaufrusetta

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/developer-scripts/blob/master/.github/Contributing.md.

## What is the current behavior?
Containers run as root users.

## Issue Number:
#371 

## What is the new behavior?
Containers run as non-root user.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?
No

## Other information

2021-01-09 01:04 UTC, lenny-intel submitted a review, later dismissed
LGTM

2021-01-09 02:27 UTC, lenny-intel commented
recheck

2021-01-09 03:11 UTC, lenny-intel commented
recheck

2021-01-09 05:21 UTC, lenny-intel commented
@cherrycl the failures on this PR look un-related. 
PR https://github.com/edgexfoundry/developer-scripts/pull/373 has similar failures and it should not fail as those changes don't impact the current TAF files. 
Please let us know if there are bugs that need to be addressed to resolve these failures.

2021-01-11 15:11 UTC, lenny-intel commented
recheck

2021-01-12 05:01 UTC, beaufrusetta commented
Looks like the Redis container runs as "root"...probably not the best idea to have the database image running super privileged. Should I attempt to modify the running user? @lenny-intel

2021-01-12 15:29 UTC, lenny-intel commented
@beaufrusetta , yes we should see if those can be run as non-root user.

2021-01-12 18:20 UTC, lenny-intel commented
recheck

2021-01-13 16:12 UTC, lenny-intel commented
recheck

2021-01-13 17:15 UTC, lenny-intel commented
recheck

2021-01-13 21:31 UTC, lenny-intel commented
@cherrycl , can you please help us determine the failures on this PR. Logs don't give mush info. THX!

2021-01-14 06:20 UTC, cherrycl commented
recheck

2021-01-14 11:44 UTC, cherrycl commented
@lenny-intel Sorry for the response lately. I tried to run the tests with this PR's change. It doesn't seem to fail on the same test cases always. Once the failure occurred I found the following error on `redis` and `core-metadata` logs. Hope it can help.
Redis log
```
1:M 14 Jan 2021 11:37:47.077 * 100 changes in 300 seconds. Saving...
1:M 14 Jan 2021 11:37:47.078 * Background saving started by pid 108
108:C 14 Jan 2021 11:37:47.079 # Failed opening the RDB file dump.rdb (in server root dir /data) for saving: Permission denied
1:M 14 Jan 2021 11:37:47.179 # Background saving error
```
core-metadata log
`level=ERROR ts=2021-01-14T11:28:43.466309048Z app=edgex-core-metadata source=deviceservice.go:83 X-Correlation-ID=6a10411d-c9d6-4342-97ab-f7bc93531b99 msg=" -> device service creation failed -> MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error."`

2021-01-14 15:18 UTC, lenny-intel commented
> Once the failure occurred I found the following error on `redis` and `core-metadata` logs. Hope it can help.
> Redis log

@cherrycl , thank you very much!

2021-01-14 15:44 UTC, lenny-intel commented
recheck

2021-01-14 16:37 UTC, lenny-intel commented
recheck

2021-01-14 17:35 UTC, lenny-intel commented
recheck

2021-01-15 15:05 UTC, lenny-intel commented
recheck

2021-01-15 15:48 UTC, lenny-intel commented
recheck

2021-01-15 16:29 UTC, lenny-intel commented
recheck

2021-01-15 17:07 UTC, lenny-intel commented
@cherrycl , @jinlinGuan , TAF smoke tests still failing on this PR. They seem unrelated, but they are passing on my PR.
Note clear why they are failing. Can you run them locally against this PR? THX!
https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fedgex-taf-pipelines/detail/smoke-test/152/tests

2021-01-18 08:59 UTC, jinlinGuan commented
@lenny-intel, I suggest we merge PR #373 first, so TAF can get the correct compose files, and that should fix the test failures. 

Because currently TAF generates the compose files that don't include the changes in this PR, for example, `security_opt` and `user` are not set for device-virtual and app services defined in TAF.

2021-01-19 15:14 UTC, lenny-intel commented
> I suggest we merge PR #373 first, so TAF can get the correct compose files

OK, we can try that.

2021-01-19 15:17 UTC, cloudxxx8 commented
we might also need to merge https://github.com/edgexfoundry/edgex-taf/pull/257

2021-01-19 15:19 UTC, lenny-intel commented
> we might also need to merge [edgexfoundry/edgex-taf#257](https://github.com/edgexfoundry/edgex-taf/pull/257)

Yes, once we mere #373 we have to merge edgexfoundry/edgex-taf#257

2021-01-19 16:48 UTC, lenny-intel commented
@beaufrusetta , I just merged my PR. Please rebase and add `user` to services in all the new partial compose files. THX!

2021-01-21 18:01 UTC, jim-wang-intel commented on compose-builder/add-mqtt-messagebus.yml
> +
This should be removed, right? has been separated out into two sections i guess

2021-01-21 19:23 UTC, lenny-intel approved these changes
LGTM

2021-01-21 19:24 UTC, lenny-intel requested changes
Need to run `make build` once more so the new TAF compose files are generated.

2021-01-21 19:57 UTC, beaufrusetta commented
> Need to run `make build` once more so the new TAF compose files are generated.

Ok - they have been updated.

2021-01-21 20:00 UTC, lenny-intel approved these changes
LGTM

2021-01-21 20:11 UTC, jim-wang-intel approved these changes

2021-01-21 21:28 UTC, merged